Module Help
    Sub ShowHelp()
        XTrace("", 0)
        XTrace("-----------------------------------------------------------------------------", 0)
        xtrace("  " & AppName & " - " & AppVer & " - Hans.van.Buitenen@freedom.nl", 0)
        xtrace("", 0)
        XTrace("  cmd /k CreateShortcut.exe N=<Name> E=<ExecutablePath> L=<ShortCutLocation> S=<Subdirectory>", 0)
        XTrace("  Where the shortcut location can be defined as:", 0)
        XTrace("    N=    is the name of the shortcut", 0)
        XTrace("    E=    is the path to the executable (or directory etc.)", 0)
        XTrace("    L=CDT is the common desktop    | " & AssignLoc("CDT"), 0)
        XTrace("    L=CSM is the common start menu | " & AssignLoc("CSM"), 0)
        XTrace("    L=CSU is the common startup    | " & AssignLoc("CSU"), 0)
        XTrace("    L=DTD is the desktop directory | " & AssignLoc("DTD"), 0)
        XTrace("    L=DT  is the desktop           | " & AssignLoc("DT"), 0)
        XTrace("    L=SM  is Start Menu            | " & AssignLoc("SM"), 0)
        XTrace("    L=SU  is the startup           | " & AssignLoc("SU"), 0)
        XTrace("    L=NS  is Network Shortcuts     | " & AssignLoc("NS"), 2)     ' Displayed ony with the v switch
        XTrace("    L=PS  is Printer Shortcuts     | " & AssignLoc("PS"), 2)     ' Displayed ony with the v switch
        XTrace("    L=W   is Windows               | " & AssignLoc("W"), 2)      ' Displayed ony with the v switch
        XTrace("", 0)
        XTrace("    L=CSMP is the common start menu| " & AssignLoc("CSMP"), 0)
        XTrace("    L=SMP  is Start Menu + Programs| " & AssignLoc("SMP"), 0)
        XTrace("    L=C:\User\Etc                  | User specified location", 0)
        XTrace("", 0)
        XTrace("    A=    Set the arguments list                                    (Optional)", 0)
        XTrace("    D=    Set the icon description or Comment field                 (Optional)", 0)
        XTrace("    I=    Set the iconlocation                                      (Optional)", 0)
        XTrace("          If none is specified then it will be set to the exe location", 0)
        XTrace("    K=    Set the shortcut key (ALT+T)                              (Optional)", 0)
        XTrace("    S=    Can be used to specify a subdirectory inside the location (Optional)", 0)
        XTrace("    W=    Set the working directory                                 (Optional)", 0)
        XTrace("", 0)
        XTrace("  Switches:", 0)
        XTrace("    -c = Create target directory if required", 0)
        XTrace("    -d = Dryrun", 0)
        XTrace("    -h, --help, /h, /? = Display this Help text", 0)
        XTrace("    -s   = Silent", 0)
        XTrace("    -t   = Translate the location", 0)
        XTrace("    -v   = Verbose", 0)
        XTrace("    --vv = Verbose more", 0)
        'XTrace("   --ts = Translate the location and set it in the environment", 0)
        XTrace("    --ws=min    = Windows style minimized", 0)
        XTrace("    --wd=<Path> = Set Working Directory (Obsolete)", 0)
        xtrace("", 0)
        xtrace("  Environment:", 0)
        xtrace("    " & DryRunStr & "=TRUE   = Test-run without creating the shortcuts", 0)
        xtrace("", 0)
        xtrace("  Examples:", 0)
        XTrace("    Display Help:", 0)
        XTrace("      >CreateShortcut.exe -h", 0)
        XTrace("", 0)
        XTrace("    Dryrun", 0)
        XTrace("      >CreateShortcut -d N=RegEdit E=C:\Windows\regedit.exe L=CSU", 0)
        XTrace("      >CreateShortcut -d N=RegEdit E=C:\Windows\regedit.exe L=CSU S=Regedit", 0)
        XTrace("", 0)
        XTrace("    Create a shortcut:", 0)
        XTrace("      >CreateShortcut N=RegEdit E=C:\Windows\regedit.exe L=SMP", 0)
        xtrace("      Create C:\Users\<user>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\RegEdit.lnk As C:\Windows\regedit.exe", 0)
        xtrace("", 0)
        XTrace("      >CreateShortcut N=RegEdit E=C:\Windows\regedit.exe L=CSMP S=Regedit -c", 0)
        XTrace("      Create directory: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Regedit", 0)
        XTrace("      Create C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Regedit\RegEdit.lnk As C:\Windows\regedit.exe", 0)
        XTrace("", 0)
        XTrace("    Show the result of DTD:", 0)
        XTrace("      >CreateShortcut.exe -d -v L=DTD", 0)
        XTrace("", 0)
        XTrace("    Translate the location ID an print the result:", 0)
        XTrace("      >CreateShortcut -t L=DTD", 0)
        XTrace("      C:\Users\Username\Desktop", 0)
        XTrace("", 0)
        XTrace("-----------------------------------------------------------------------------", 0)
        XTrace("", 0)
    End Sub

End Module
